apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vmit61aw3-go
  janus-idp.io/tekton: vmit61aw3-go
  backstage.io/kubernetes-id: vmit61aw3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vmit61aw3-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
