apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vmit61aw3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vmit61aw3-go 
  name: vmit61aw3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vmit61aw3-go 
